export const LAB_SERVICE_CATALOG = [
  {
    value: 'ortodoncia',
    label: 'Ortodoncia',
    materials: ['Acrílico', 'Alambre', 'Bandas', 'Tornillo de expansión', 'Resortes', 'Otro'],
    services: [
      'Aparato Spring Retainer',
      'Aparato arco lingual (fijo con bandas)',
      'Aparato arco de Nance (fijo con bandas)',
      'Aparato de ortodoncia barra transpalatal',
      'Placa con tornillo de expansión',
      'Placa con tornillo de acción sagital',
      'Placa con tornillo de expansión de abanico',
      'Placa trampa lingual',
      'Placa Hawley con pistas',
      'Aparato Quad Helix sup. y Quad Action inf.',
      'Aparato Six Helix sup. y Bi-Helix inf.',
      'Aparato Hayrax sup. y aparato Hass inf.',
      'Aparato de ortodoncia Bionator',
      'Placa con tornillo de expansión tridireccional',
      'Placa Hawley tipo péndulo',
      'Placas con tornillo Hayrax o bandas (4)',
      'Soldar tubos a bandas',
      'Placa Hawley (Onley)',
      'Placa plano inclinado',
      'Placa Hawley con resortes cantiliver o en ballesta',
      'Placas de contención o retención',
      'Placa trampa chupa dedos',
      'Aparato de ortodoncia con arco W',
      'Aparato Lip Bumper',
      'Mantenedor de espacio 3/U',
      'Pantalla oral',
      'Zapatilla distal (1 banda o 1 corona)',
    ],
  },
  {
    value: 'prostodoncia',
    label: 'Prostodoncia',
    materials: ['Acrílico Nic Tone', 'Acrílico Opti Cryl', 'Acrirock', 'Transparente', 'Dorada', 'Yeso piedra', 'Yeso Velmix', 'Otro'],
    services: [
      'Juego de prostodoncia total en acrílicos NicTone',
      'Juego de prostodoncia total en acrílico Opti Cryl',
      'Prostodoncia parcial dientes Acrirock',
      'Gancho Wipla o bola',
      'Ganchos vaciados',
      'Refuerzo metálico vaciado',
      'Paladar transparente',
      'Maya dorada',
      'Aumento pieza prefabricada',
      'Reparación de placa acrílica',
      'Rebase de placa',
      'Cambio de base por placa',
      'Ganchos de cruz',
      'Cucharilla individual',
      'Guarda rígida',
      'Guarda blanda',
      'Encerado diagnóstico con llave de silicona',
      'Llenado de modelos yeso piedra',
      'Llenado de modelos yeso Velmix',
      'Servicio sanitario prostodoncia',
    ],
  },
  {
    value: 'protesis_fija',
    label: 'Prótesis fija',
    materials: ['Acrílico Nic Tone', 'Acrilux', 'Autocurable', 'Metal cerámico', 'Metal porcelana', 'Cerómero', 'Zirconia', 'Liga de plata', 'Otro'],
    services: [
      'Unidad acrílico Nic Tone',
      'Unidad acrílico Acrilux',
      'Unidad de acrílico autocurable',
      'Corona metal cerámico',
      'Incrustación de metal cerámico',
      'Endoposte metal cerámico',
      'Corona veneer 3/4 o 4/5 estético cerómero',
      'Corona metal porcelana',
      'Cerómero (Parafil Lab)',
      'Zirconia',
      'Corona total liga de plata',
      'Incrustación liga de plata',
      'Endoposte liga de plata',
      'Corona 3/4, 4/5 liga de plata',
    ],
  },
  {
    value: 'protesis_removible',
    label: 'Prótesis removible',
    materials: ['Cromo', 'Valplast', 'Acrílico', 'Otro'],
    services: [
      'Puente removible chico unilateral de 1 a 2 piezas',
      'Puente removible chico unilateral de 3 a 4 piezas',
      'Removible mediano de 5 a 8 piezas',
      'Removible mediano de 9 a 12 piezas',
      'Espiga soldada para aumento',
      'Soldaduras de removible en cromo',
      'Prótesis chica unilateral de 1 a 3 pieza',
      'Prótesis chica bilateral de 3 a 4 piezas',
      'Prótesis mediana de 5 a 8 piezas',
      'Prótesis grande de 9 a 12 piezas',
      'Prótesis total',
      'Aumento por pieza',
    ],
  },
] as const;

export const DENTAL_PIECES = [
  ['18', '17', '16', '15', '14', '13', '12', '11'],
  ['21', '22', '23', '24', '25', '26', '27', '28'],
  ['48', '47', '46', '45', '44', '43', '42', '41'],
  ['31', '32', '33', '34', '35', '36', '37', '38'],
];

export const getServiceCategory = (value: string) =>
  LAB_SERVICE_CATALOG.find((category) => category.value === value) || LAB_SERVICE_CATALOG[0];

